remote_theme: obscurefreeman/profile-theme

title: 晦涩弗里曼
description: 个人资料徽章
permalinks: pretty

lang: zh
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4

# Navbar
navbar_link_text: 我的个人资料
navbar_button_text: 改进此页面 GitHub
